### ISSUE TITLE
optparse.OptionConflictError in flake8 v3.7.0

### ISSUE THREAD

**Issue by rossmacarthur** [snoack/flake8-per-file-ignores#9]
I just upgraded to flake8 v3.7.0. And I get the following issue:

```
Traceback (most recent call last):
  File "~/.pyenv/versions/3.7.1/envs/venv/bin/flake8", line 10, in <module>
    sys.exit(main())
  File "~/.pyenv/versions/3.7.1/envs/venv/lib/python3.7/site-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "~/.pyenv/versions/3.7.1/envs/venv/lib/python3.7/site-packages/flake8/main/application.py", line 392, in run
    self._run(argv)
  File "~/.pyenv/versions/3.7.1/envs/venv/lib/python3.7/site-packages/flake8/main/application.py", line 379, in _run
    self.initialize(argv)
  File "~/.pyenv/versions/3.7.1/envs/venv/lib/python3.7/site-packages/flake8/main/application.py", line 363, in initialize
    self.register_plugin_options()
  File "~/.pyenv/versions/3.7.1/envs/venv/lib/python3.7/site-packages/flake8/main/application.py", line 204, in register_plugin_options
    self.check_plugins.register_options(self.option_manager)
  File "~/.pyenv/versions/3.7.1/envs/venv/lib/python3.7/site-packages/flake8/plugins/manager.py", line 490, in register_options
    list(self.manager.map(register_and_enable))
  File "~/.pyenv/versions/3.7.1/envs/venv/lib/python3.7/site-packages/flake8/plugins/manager.py", line 296, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "~/.pyenv/versions/3.7.1/envs/venv/lib/python3.7/site-packages/flake8/plugins/manager.py", line 486, in register_and_enable
    call_register_options(plugin)
  File "~/.pyenv/versions/3.7.1/envs/venv/lib/python3.7/site-packages/flake8/plugins/manager.py", line 398, in generated_function
    return method(optmanager, *args, **kwargs)
  File "~/.pyenv/versions/3.7.1/envs/venv/lib/python3.7/site-packages/flake8/plugins/manager.py", line 221, in register_options
    add_options(optmanager)
  File "~/.pyenv/versions/3.7.1/envs/venv/lib/python3.7/site-packages/flake8_per_file_ignores.py", line 82, in add_options
    parser.add_option('--per-file-ignores', parse_from_config=True)
  File "~/.pyenv/versions/3.7.1/envs/venv/lib/python3.7/site-packages/flake8/options/manager.py", line 230, in add_option
    self.parser.add_option(option.to_optparse())
  File "~/.pyenv/versions/3.7.1/lib/python3.7/optparse.py", line 1008, in add_option
    self._check_conflict(option)
  File "~/.pyenv/versions/3.7.1/lib/python3.7/optparse.py", line 983, in _check_conflict
    option)
optparse.OptionConflictError: option --per-file-ignores: conflicting option string(s): --per-file-ignores
```

**Comment by rossmacarthur** [comment]
Oh I see it looks like this option exists in flake8 v3.7.0. See http://flake8.pycqa.org/en/latest/user/options.html?highlight=per-file-ignores#cmdoption-flake8-per-file-ignores it works slightly differently to this package though, I had to adjust my flake8 config.

**Comment by barbossa** [comment]
I've encountered with the same issue today

**Comment by snoack** [comment]
I saw that coming up. flake8 3.7.0 introduced a built-in `per-ignore-files` option. The semantics differ slightly from this extension, but it doesn't seem worth to restore compatibility and keep maintaining the `flake8-per-file-ignores` extension as most of its functionality is now built into flake. I will update the `README` and `setup.py` to indicate incompatibility with flake8 >= 3.7.0
